update install script

diff --git a/StartWine_v421 b/StartWine_v421
--- a/StartWine_v421
+++ b/StartWine_v421
@@ -1,28 +1,42 @@
 #!/usr/bin/env bash
-################################################################################
 
-if [ "$EUID" = 0 ]; then
+RED="\033[1;91m"
+BLUE="\033[1;94m"
+GREEN="\033[1;92m"
+YELLOW="\033[1;33m"
+RESETCOLOR="\033[1;00m"
+
+print_error () { echo -e "${RED}[ ERROR ][$(date +"%Y.%m.%d %T")]: $* $RESETCOLOR" ; }
+
+print_info () { echo -e "${GREEN}[ INFO ][$(date +"%Y.%m.%d %T")]: $* $RESETCOLOR" ; }
+
+print_warning () { echo -e "${YELLOW}[ WARNING ][$(date +"%Y.%m.%d %T")]: $* $RESETCOLOR" ; }
+
+if [ "${EUID}" == 0 ]; then
     clear
-    echo "####  Please do not run this script as root!  ####"
+    print_error "Please do not run this script as root!"
     exit 1
 fi
 
-export SW_GIT_VER="408"
-export UTILS_GIT_VER="2.6"
-export RUNTIME_GIT_VER="0.8"
-export PFX_DEF_GIT_VER="0.2"
+#    version
+export SW_GIT_VER="421"
+export SW_RUNTIME_GIT_VER="14"
 
-[ ! -d "$HOME/.config" ] && \
-    mkdir -p "$HOME/.config"
+[ ! -d "${HOME}/.config" ] && \
+    mkdir -p "${HOME}/.config"
 
-[ ! -d "$HOME/.local/bin" ] && \
-    mkdir -p "$HOME/.local/bin"
+[ ! -d "${HOME}/.local/bin" ] && \
+    mkdir -p "${HOME}/.local/bin"
 
-if [ -f "$HOME/.config/swrc" ]; then
-    START_WINE_PATH="$(cat "$HOME/.config/swrc")"
+[ ! -d "${HOME}/.local/share/applications" ] && \
+    mkdir -p "${HOME}/.local/share/applications"
+
+if [ -f "${HOME}/.config/swrc" ]; then
+    START_WINE_PATH="$(cat "${HOME}/.config/swrc"|head -n1)"
     export START_WINE_PATH
 else
-    export START_WINE_PATH="$HOME/.local/share/StartWine"
+    START_WINE_PATH="${HOME}/.local/share/StartWine"
+    export START_WINE_PATH
 fi
 
 [ -n "$(tty|grep -v 'not a'|grep -Eo 'tty|pts')" ] && \
@@ -30,50 +44,65 @@ fi
 
 export SW_RUNTIME="${START_WINE_PATH}/data/runtime/sw_runtime"
 
-if [ -d "${START_WINE_PATH}" ]; then
+[ -d "${START_WINE_PATH}" ] && \
     export DIRECTORY_EXIST="true"
-else
-    export DIRECTORY_EXIST="false"
-fi
 
 [ ! -d "${START_WINE_PATH}/data/tmp" ] && \
     mkdir -p "${START_WINE_PATH}/data/tmp"
 
-if [ -f "${START_WINE_PATH}/data/tools/utils/version" ]; then
-    UTILS_VER="$(cat "${START_WINE_PATH}/data/tools/utils/version" | tr -d "[:alpha:][:punct:]")"
-    export UTILS_VER
-fi
-
 if [ -f "${START_WINE_PATH}/data/runtime/version" ]; then
-    RUNTIME_VER="$(cat "${START_WINE_PATH}/data/runtime/version" | tr -d "[:alpha:][:punct:]")"
-    export RUNTIME_VER
-fi
-
-if [ -f "${START_WINE_PATH}/data/pfx_backup/version" ]; then
-    PFX_DEF_VER="$(cat "${START_WINE_PATH}/data/pfx_backup/version" | tr -d "[:alpha:][:punct:]")"
-    export PFX_DEF_VER
+    SW_RUNTIME_CURRENT_VER="$(cat "${START_WINE_PATH}/data/runtime/version")"
+    export SW_RUNTIME_CURRENT_VER
 fi
 
 if [ -f "${START_WINE_PATH}/data/scripts/version" ]; then
-    SCRIPT_VER="$(cat "${START_WINE_PATH}/data/scripts/version")"
-    export SCRIPT_VER
+    SW_CURRENT_VER="$(cat "${START_WINE_PATH}/data/scripts/version")"
+    export SW_CURRENT_VER
 fi
 
-UTILS_FORMAT_VER="$(echo "${UTILS_GIT_VER}" | tr -d "[:alpha:][:punct:]")"
-export UTILS_FORMAT_VER
+sw_check_url () {
 
-RUNTIME_FORMAT_VER="$(echo "${RUNTIME_GIT_VER}" | tr -d "[:alpha:][:punct:]")"
-export RUNTIME_FORMAT_VER
+    timeout=3
+    tmp_file=$(mktemp)
+    URL_DOWNLOAD=""
 
-PFX_DEF_FORMAT_VER="$(echo "${PFX_DEF_GIT_VER}" | tr -d "[:alpha:][:punct:]")"
-export PFX_DEF_FORMAT_VER
+    check_speed() {
+        export url=$1
+
+        res=$(curl -r 0-10485760 -L -s -m $timeout -o /dev/null -w "%{http_code} %{speed_download}" "$url" 2>/dev/null)
+        status=$(echo $res | cut -d' ' -f1)
+        speed=$(echo $res | cut -d' ' -f2 | cut -d'.' -f1)
+
+        if [[ "$status" =~ ^2[0-9]{2}$ ]]; then
+            speed_mb=$(awk -v s="$speed" 'BEGIN {printf "%.2f", s / 1048576}')
+            print_info "URL: ${url:0:40}... | STATUS: $status | SPEED: $speed_mb MB/s"
+            echo "$speed $url" >> "$tmp_file"
+        else
+            print_error "URL: ${url:0:40}... | STATUS: $status | SKIP (ERROR: or Unavailable)"
+        fi
+    }
+
+    for url in "${FTP_URL[@]}"; do
+        check_speed "$url" &
+    done
+
+    wait
+
+    if [ -s "$tmp_file" ]; then
+        best_result=$(sort -rn "$tmp_file" | head -n 1)
+        URL_DOWNLOAD=$(echo "$best_result" | cut -d' ' -f2-)
+        echo "---------------------------------------"
+        print_info "Fastest available URL: $URL_DOWNLOAD"
+    else
+        echo "---------------------------------------"
+        print_error "None of the servers are accessible."
+    fi
+
+    rm -f "$tmp_file"
+
+}
 
 try_download () {
-
-    export RED='\033[1;91m'
-    export BLUE='\033[1;94m'
-    export GREEN='\033[1;92m'
-    export RESETCOLOR='\033[1;00m'
 
     if [ ! -n "$(tty|grep -v 'not a'|grep -Eo 'tty|pts')" ]; then
         export NOT_TERM=1
@@ -265,7 +294,7 @@ try_download () {
                     dl_progress
                 elif is_exist curl ; then
                     curl -R --progress-bar --insecure --fail -L "$URL" -o \
-                    "$FILEDIR/$FILENAME" |& tr '\r' '\n'|\
+                    "$FILEDIR/$FILENAME" |& tr '\r' '\n'|sed '0,/100/{/100/d;}'|\
                     sed -ur 's|[# ]+||g;s|.*=.*||g;s|.*|#Downloading at &\n&|g'|\
                     dl_progress
                 elif is_exist wget2 ; then
@@ -305,130 +334,118 @@ try_download () {
 
 }
 
-if [[ "$UTILS_VER" -lt "$UTILS_FORMAT_VER" ]]; then
-    [ -d "${START_WINE_PATH}/data/tools/utils" ] && \
-        rm -rf "${START_WINE_PATH}/data/tools/utils"
-fi
-
-if [[ "$PFX_DEF_VER" -lt "$PFX_DEF_FORMAT_VER" ]]; then
-    [ -f "${START_WINE_PATH}/data/pfx_backup/pfx_default.iso" ] && \
-        rm -rf "${START_WINE_PATH}/data/pfx_backup/pfx_default.iso"
-fi
-
-if [[ "$RUNTIME_VER" < "$RUNTIME_FORMAT_VER" ]]; then
-
-    export URL_RUNTIME_LIST=(
-       "https://huggingface.co/SudoNano/sw_repo/resolve/main/runtime/sw_runtime.iso?download=true"
-       "https://github.com/RusNor/sw_runtime/releases/download/sw_runtime/sw_runtime.iso"
-    )
-
-    [ ! -d "${START_WINE_PATH}/data/runtime" ] && \
-        mkdir -p "${START_WINE_PATH}/data/runtime"
+if [[ "${SW_RUNTIME_CURRENT_VER}" -lt "${SW_RUNTIME_GIT_VER}" ]]; then
 
     [ -f "${SW_RUNTIME}" ] && \
         rm -rf "${SW_RUNTIME}"
 
-    try_download "${URL_RUNTIME_LIST[0]}" "${SW_RUNTIME}" \
-    || try_download "${URL_RUNTIME_LIST[1]}" "${SW_RUNTIME}" &&
-    chmod +x "${SW_RUNTIME}"
+    [ ! -d "${START_WINE_PATH}/data/runtime" ] && \
+        mkdir -p "${START_WINE_PATH}/data/runtime"
 
-    if [ -f "${SW_RUNTIME}" ]; then
-        [ ! -f "$HOME/.local/bin/sw" ] && \
-            ln -sfr "${SW_RUNTIME}" "$HOME/.local/bin/sw"
+    export FTP_URL=(
+        "https://startwine-launcher.ru/StartWine-data/runtime/sw_runtime.iso"
+        "https://huggingface.co/StartWine/sw_repo/resolve/main/runtime/sw_runtime.iso?download=true"
+        "https://github.com/RusNor/sw_runtime/releases/download/sw_runtime/sw_runtime.iso"
+    )
 
-        [ ! -f "${START_WINE_PATH}/data/runtime/sw" ] && \
+    sw_check_url
+
+    if try_download "${URL_DOWNLOAD}" "${SW_RUNTIME}"; then
+
+        chmod +x "${SW_RUNTIME}"
+
+        [ ! -L "${START_WINE_PATH}/data/runtime/sw" ] && \
             ln -sfr "${SW_RUNTIME}" "${START_WINE_PATH}/data/runtime/sw"
 
-        echo "${RUNTIME_GIT_VER}" > "${START_WINE_PATH}/data/runtime/version"
+        echo "${SW_RUNTIME_GIT_VER}" > "${START_WINE_PATH}/data/runtime/version"
+        print_info "Download completed successfully"
+    else
+        print_error "Failed to download sw_runtime from (repo), please run the installation again."
+        exit 1
     fi
 
 fi
 
-if [[ "$SCRIPT_VER" -lt "$SW_GIT_VER" ]]; then
+if [[ "${SW_CURRENT_VER}" -lt "${SW_GIT_VER}" ]]; then
 
-    [ -d "${START_WINE_PATH}/data/scripts" ] && \
-        rm -rf "${START_WINE_PATH}/data/scripts"
+    [ -L "$HOME/.local/bin/sw" ] && \
+        rm "$HOME/.local/bin/sw"
 
-    [ -d "${START_WINE_PATH}/data/img/gui_icons" ] && \
-        rm -rf "${START_WINE_PATH}/data/img/gui_icons"
+    [ -f "${HOME}/.cache/sw_fm/exe_data.json" ] && \
+        rm -rf "${HOME}/.cache/sw_fm/exe_data.json"
 
-    [ -d "${START_WINE_PATH}/data/img/sw_themes/sounds" ] && \
-        rm -rf "${START_WINE_PATH}/data/img/sw_themes/sounds"
+    [ -d "${START_WINE_PATH}/data/tools/utils" ] && \
+        rm -rf "${START_WINE_PATH}/data/tools/utils"
 
-    [ -d "${START_WINE_PATH}/data/img/sw_themes/css/assets" ] && \
-        rm -rf "${START_WINE_PATH}/data/img/sw_themes/css/assets"
+    [ -f "${START_WINE_PATH}/data/pfx_backup/pfx_default.iso" ] && \
+        rm -rf "${START_WINE_PATH}/data/pfx_backup/pfx_default.iso"
 
-    [ -d "${START_WINE_PATH}/data/img/sw_themes/css/dark" ] && \
-        rm -rf "${START_WINE_PATH}/data/img/sw_themes/css/dark"
+    [ -f "${HOME}/.local/share/applications/StartWine.desktop" ] && \
+        rm -rf "${HOME}/.local/share/applications/StartWine.desktop"
 
-    [ -d "${START_WINE_PATH}/data/img/sw_themes/css/light" ] && \
-        rm -rf "${START_WINE_PATH}/data/img/sw_themes/css/light"
+    [ -f "${HOME}/.local/share/applications/StartWineShell.desktop" ] && \
+        rm -rf "${HOME}/.local/share/applications/StartWineShell.desktop"
 
-    [ -f "${START_WINE_PATH}/data/img/sw_themes/css/default.css" ] && \
-        rm -rf "${START_WINE_PATH}/data/img/sw_themes/css/default.css"
+    [ -f "${HOME}/.local/share/applications/ru.launcher.StartWine.desktop" ] && \
+        rm -rf "${HOME}/.local/share/applications/ru.launcher.StartWine.desktop"
 
-    [ -d "${START_WINE_PATH}/data/img/launcher_icons" ] && \
-        rm -rf "${START_WINE_PATH}/data/img/launcher_icons"
-
-    [ -f "$HOME/.local/share/applications/StartWine.desktop" ] && \
-        rm -rf "$HOME/.local/share/applications/StartWine.desktop"
-
-    if [ -f "/usr/share/applications/StartWine.desktop" ]; then
-
-        [ ! -d "$HOME/.local/share/applications" ] && \
-            mkdir -p "$HOME/.local/share/applications"
-
-        {
-            echo "[Desktop Entry]"
-            echo "Name=StartWine"
-            echo "Exec=startwine %F"
-            echo "Comment[en_GB]=Launch Windows applications on Linux operating systems"
-            echo "Comment[ru]=Запуск приложений Windows в операционных системах Linux"
-            echo "Type=Application"
-            echo "MimeType=application/x-wine-extension-msp;application/x-msi;application/x-ms-dos-executable;"
-            echo "Categories=Game;"
-            echo "Icon=StartWine.png"
-        } > "${HOME}/.local/share/applications/StartWine.desktop"
-
-        chmod +x "${HOME}/.local/share/applications/StartWine.desktop"
+    if [ -f "/usr/share/applications/ru.launcher.StartWine.desktop" ]; then
+        cp -f "/usr/share/applications/ru.launcher.StartWine.desktop" && \
+        "${HOME}/.local/share/applications"
     fi
-
-    export START_WINE_EXTRACT="$(dirname "${START_WINE_PATH}")"
-
-    export URL_VER="https://github.com/RusNor/StartWine-Launcher/releases/download/StartWine_v$SW_GIT_VER/StartWine_v$SW_GIT_VER.tar.xz"
-
-    try_download "${URL_VER}" "${START_WINE_PATH}/data/tmp/StartWine_v$SW_GIT_VER.tar.xz" \
-    || rm -rf "${START_WINE_PATH}/data/tmp/StartWine_v$SW_GIT_VER.tar.xz"
-
-    echo "Download complete succsessfully."
 
     if [ -f "${SW_RUNTIME}" ]; then
 
-        "${SW_RUNTIME}" tar -xvf "${START_WINE_PATH}/data/tmp/StartWine_v$SW_GIT_VER.tar.xz" -C "${START_WINE_EXTRACT}" \
-        || rm -rf "${START_WINE_PATH}/data/scripts"
+        export FTP_URL=(
+           "https://startwine-launcher.ru/StartWine-data/releases/StartWine_v${SW_GIT_VER}.tar.xz"
+           "https://huggingface.co/StartWine/sw_repo/resolve/main/release/StartWine_v${SW_GIT_VER}.tar.xz?download=true"
+           "https://github.com/RusNor/StartWine-Launcher/releases/download/StartWine_v${SW_GIT_VER}/StartWine_v${SW_GIT_VER}.tar.xz"
+        )
 
-        [ -d "${START_WINE_PATH}/data/tmp/StartWine" ] && \
-            rm -rf "${START_WINE_PATH}/data/tmp/StartWine"
+        sw_check_url
 
-        [ -f "${START_WINE_PATH}/data/tmp/StartWine_v$SW_GIT_VER.tar.xz" ] && \
-            rm -rf "${START_WINE_PATH}/data/tmp/StartWine_v$SW_GIT_VER.tar.xz"
+        if try_download "${URL_DOWNLOAD}" "${START_WINE_PATH}/data/tmp/StartWine_v${SW_GIT_VER}.tar.xz"; then
+            print_info "Download completed successfully"
+            START_WINE_EXTRACT="$(dirname "${START_WINE_PATH}")"
+            export START_WINE_EXTRACT
 
-        if [ $DIRECTORY_EXIST == "true" ]; then
-            "${START_WINE_PATH}/data/runtime/sw" "$@" ; exit 0
+            if [ "${DIRECTORY_EXIST}" == "true" ]; then
+                "${START_WINE_PATH}/data/runtime/sw" --shutdown
+                "${START_WINE_PATH}/data/runtime/sw_runtime" rim-kill all
+            fi
+
+            if "${SW_RUNTIME}" tar -xvJf "${START_WINE_PATH}/data/tmp/StartWine_v${SW_GIT_VER}.tar.xz" -C "${START_WINE_EXTRACT}"; then
+                print_info "Unpacking completed successfully"
+                echo "${SW_GIT_VER}" > "${START_WINE_PATH}/data/scripts/version"
+            else
+                print_error "Failed to unpack archive"
+            fi
+
         else
-            "${START_WINE_PATH}/data/runtime/sw" --path "${START_WINE_PATH}" "$@" 2>/dev/null ; exit 0
+            print_error "Failed to download archive from (repo), please run the installation again..."
+            exit 1
         fi
+
+        if [ "${DIRECTORY_EXIST}" == "true" ]; then
+            "${START_WINE_PATH}/data/runtime/sw_runtime" "${START_WINE_PATH}/data/scripts/sw_runlib"
+            print_info "StartWine update to version ${SW_GIT_VER} completed successfully"
+        else
+            "${START_WINE_PATH}/data/runtime/sw" --path "${START_WINE_PATH}" "$@" 2>/dev/null
+
+            START_WINE_PATH="$(cat "${HOME}/.config/swrc"|head -n1)"
+            export START_WINE_PATH
+
+            "${START_WINE_PATH}/data/runtime/sw_runtime" "${START_WINE_PATH}/data/scripts/sw_runlib"
+            print_info "Installation completed successfully"
+        fi
+
+        exit 0
     else
-        [ -d "${START_WINE_PATH}/data/tmp/StartWine" ] && \
-            rm -rf "${START_WINE_PATH}/data/tmp/StartWine"
-
-        [ -f "${START_WINE_PATH}/data/tmp/StartWine_v$SW_GIT_VER.tar.xz" ] && \
-            rm -rf "${START_WINE_PATH}/data/tmp/StartWine_v$SW_GIT_VER.tar.xz"
-
-        echo "ERROR: $SW_RUNTIME not exists!"
+        print_error "${SW_RUNTIME} not exists!"
+        exit 1
     fi
 else
-    "${START_WINE_PATH}/data/runtime/sw" "$@" ; exit 0
+    "${START_WINE_PATH}/data/runtime/sw" "$@"
+    exit 0
 fi
 
-################################################################################
